name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        cd hello-web-app
        docker build -t hello-web-app:${{ github.sha }} .
        docker build -t hello-web-app:latest .
    
    - name: Test Docker container
      run: |
        # Start container in background
        docker run -d -p 8080:8080 --name test-container hello-web-app:latest
        
        # Wait for container to start
        sleep 10
        
        # Test if app responds
        curl -f http://localhost:8080 || exit 1
        
        # Stop and remove container
        docker stop test-container
        docker rm test-container
    
    - name: Login to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Push to Docker Hub
      if: github.event_name == 'push'
      run: |
        docker tag hello-web-app:latest ${{ secrets.DOCKER_USERNAME }}/hello-web-app:latest
        docker tag hello-web-app:latest ${{ secrets.DOCKER_USERNAME }}/hello-web-app:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/hello-web-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/hello-web-app:${{ github.sha }}
